syntax enable
set nu
set expandtab
set tabstop=4
set shiftwidth=4
set showmatch
set incsearch
set hlsearch
set autoindent
set nocompatible
colors ron
" hi Pmenu ctermfg=7 ctermbg=236
hi PmenuSel ctermfg=white ctermbg=32
hi CocFloating ctermfg=black ctermbg=240

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'easymotion/vim-easymotion'
Plug 'preservim/nerdtree'
Plug 'vim-scripts/DoxygenToolkit.vim'
call plug#end()

let g:coc_global_extensions = ['coc-json', 'coc-cmake', 'coc-clangd', 'coc-sh', 'coc-highlight']
let g:DoxygenToolkit_authorName = "croquettess"
let g:DoxygenToolkit_projectNumber = ""

let mapleader=" "
nmap qq :q!<Cr>
nmap <leader>w :w<Cr>
nmap s ""
nmap H ^
nmap L $
nmap <leader>s <Plug>(easymotion-s2)
nmap <leader>m :NERDTree<Cr>
nmap <leader>df :Dox<Cr>
nmap <leader>dh :DoxAuthor<Cr>
nmap <leader>h <C-w>h
nmap <leader>j <C-w>j
nmap <leader>k <C-w>k
nmap <leader>l <C-w>l
nmap <leader>+ <C-w>+
nmap <leader>- <C-w>-
nmap <leader>< <C-w><
nmap <leader>> <C-w>>


imap jj <esc>
imap <C-h> <Left>
imap <C-j> <Down>
imap <C-k> <Up>
imap <C-l> <Right>

vmap H ^
vmap L $

autocmd FileType c,cpp,cc,h,hpp setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre *.c,*.cpp,*.h,*.hpp,*.cc :%!clang-format
autocmd BufWritePre * if getline(line('$')) !~# '^\s*$' | call append(line('$'), '') | endif

